dataFiles:
    inVCF:
        disk:
            path:
                - 1kg.micro.vcf.bgz
    outMT:
        disk:
            path: 1kg.ma.mt
        memory:

executionPlan:
    - IGTVCF
stages:
    IGTVCF:
        spec:
            function: ImportGenotype
        ios:
            input:
                id: inVCF
                direction: input
            output:
                id: outMT
                direction: output