order:
    - IGTVCF
stages:
    IGTVCF:
        spec:
            function: ImportGenotype
        io:
            input:
                direction: input
                path: 1kg.micro.vcf.bgz
            output:
                direction: output
                path: 1kg.ma.mt