order:
    - BRKMA
stages:
    BRKMA:
        spec:
            function: SplitMulti
        arg:
            withHTS: true
        io:
            input:
                direction: input
                path: 1kg.ma.mt
            output:
                direction: output
                path: 1kg.ba.mt