defaults:
    localMode: false
    numSgeJobs:
        default: 256
        min: 1
        max: 1024
dataFiles:
    inVCF:
        disk:
            path: 1kg.micro.vcf.bgz
            isProduced: true

    outVCF:
        disk:
            path: 1kg.micro.out.vcf.bgz

    vepVCF:
        disk:
            path: 1kg.micro.vep.vcf.bgz
            exportParam:
                parallel: separate_header

    vepDIR:
        disk:
            path: 1kg.micro.vep
            format: dir

    vepVar:
        disk:
            path: 1kg.micro.vep.var.ht

    vepClVar:
        disk:
            path: 1kg.micro.vep.clvar.ht

    vepFreq:
        disk:
            path: 1kg.micro.vep.freq.ht

    vepConseq:
        disk:
            path: 1kg.micro.vep.conseq.ht

    vepConseqVar:
        disk:
            path: 1kg.micro.vep.conseqVar.ht

    vepConseqTerms:
        disk:
            path: 1kg.micro.vep.conseqTerms.ht

    vepVarTerms:
        disk:
            path: 1kg.micro.vep.varTerms.ht

    vepConseqWithVarId:
        disk:
            path: vepConseqWithVarId.ht
            isProduced: true

    outMt:
        disk:
            path: out.mt
            isProduced: true

    outGene:
        disk:
            path: outGene.ht
            isProduced: true

    
    inPheno:
        disk:
            path: 1kg.pheno.tsv
            isProduced: true
            importParam:
                impute: True
    outPheno:
        disk:
            path: 1kg.pheno.ht

    pcaScore:
        disk:
            path: 1kg.pca.ht
            isProduced: true

    outPval1:
        disk:
            path: 1kg.pval1.ht

    outPval2:
        disk:
            path: 1kg.pval2.ht

#gzip -dc 1kg.micro2.vcf.bgz | head -n 98 | tail | cut -f 1-10 | column -t

executionPlan:
    # - CO1
    # - EGTVEP
    # - VEPANN
    # - VEPLT1
    # - VEPLT2
    # - VEPLT3
    # - VEPLT4
    # - JOINVEP
    # - JOINVEP2
    # - PCA
    # - ASSOC1
    - ASSOC2

stages:
    CO1:
        specifications:
            function: ByPass
        inouts:
            inData:
                dataFileId: inVCF
                microFunctions:
                    -   type: rename
                        parameters:
                            s: sample
                    -   type: addId
                        parameters:
                            sampleId: sample
                            variantId: CHR:POS:ALLELES
            outData:
                dataFileId: outMt

    EGTVEP:
        specifications:
            function: ByPass
        inouts:
            inData:
                dataFileId: outMt
            outData:
                dataFileId: vepVCF
                microFunctions:
                    -   type: forVep
                    -   type: repartition
                        parameters:
                            numPartitions: 1
    
    CO2:
        specifications:
            function: ByPass
        inouts:
            inData:
                dataFileId: outMt
            outData:
                dataFileId: outVCF

    VEPANN:
        specifications:
            function: VepAnnotation
        parameters:
            isArrayJob: true
            vepCli: 
                - bash
                - /home/arabay/cap/scripts/run-sge-array.sh
                - __VCF_DIR__
                - __JSON_DIR__
                - __TBL_DIR__
                - __JOB_DIR__
                - __JOB_NAME__
                - __JOB_START__
                - __JOB_END__
                - __JOB_IN_PARALLEL__
                - /home/arabay/cap/scripts
        inouts:
            inData:
                dataFileId: vepVCF
            outData:
                dataFileId: vepDIR

    VEPLT1:
        specifications:
            function: VepLoadTables
        parameters:
            tables:
                - var
        inouts:
            inData:
                dataFileId: vepDIR
            outVar:
                dataFileId: vepVar
            
    VEPLT2:
        specifications:
            function: VepLoadTables
        parameters:
            tables:
                - clvar
        inouts:
            inData:
                dataFileId: vepDIR
            outClVar:
                dataFileId: vepClVar
    VEPLT3:
        specifications:
            function: VepLoadTables
        parameters:
            tables:
                - freq
        inouts:
            inData:
                dataFileId: vepDIR
            outFreq:
                dataFileId: vepFreq
    VEPLT4:
        specifications:
            function: VepLoadTables
        parameters:
            tables:
                - conseq
        inouts:
            inData:
                dataFileId: vepDIR
            outConseq:
                dataFileId: vepConseq
            outConseqVar:
                dataFileId: vepConseqVar
            outConseqTerms:
                dataFileId: vepConseqTerms
            outVarTerms:
                dataFileId: vepVarTrems

    JOINVEP:
        specifications:
            function: Join
        parameters:
            order:
                -   table: inData_01
                -   table: inData_02
                    kind: join
                    how: inner
        inouts:
            inData_01:
                dataFileId: vepConseq
            inData_02:
                dataFileId: vepConseqVar
            outData:
                dataFileId: vepConseqWithVarId
                microFunctions:
                    -   type: keyBy
                        parameters:
                            keys:
                                - varId
                    -   type: select
                        parameters:
                            expr:
                                - gene_symbol

    JOINVEP2:
        specifications:
            function: Join
        parameters:
            order:
                -   table: inData_02
                -   table: inData_01
                    kind: annotate
                    axis: rows
                    namedExpr:
                        locus: inTable[outTable.varId].locus
                        alleles: inTable[outTable.varId].alleles
                        skat_weight: inTable[outTable.varId].skat_weight
        inouts:
            inData_01:
                dataFileId: outMt
                microFunctions:
                    -   type: keyBy
                        parameters:
                            axis: rows
                            keys:
                                - variantId
                    -   type: annotate
                        parameters:
                            axis: rows
                            namedExpr:
                                maf: hl.min(hl.agg.call_stats(data.GT,data.alleles).AF)
                    -   type: annotate
                        parameters:
                            axis: rows
                            namedExpr:
                                skat_weight: hl.dbeta(data.maf,1.0,25.0)**2
                    -   type: describe

            inData_02:
                dataFileId: vepConseqWithVarId
            outData:
                dataFileId: outGene
                microFunctions:
                    -   type: keyBy
                        parameters:
                            keys:
                                - locus
                                - alleles

    PCA:
        specifications:
            function: PcaHweNorm
        parameters:
            numPcaVectors: 3
        inouts:
            inData:
                dataFileId: outMt
            outScores:
                dataFileId: pcaScore

    ASSOC1:
        specifications:
            function: HailAssociation
        parameters:
            tests:
                -   type: LogReg
                    subType: wald
                    covariates:
                        -   table: inTable_01
                            cols:
                                - scores_1
                                - scores_2
                                - scores_3
                    responseVariables:
                        -   tableId: inTable_02
                            cols:
                                -   colName: t2d
                                    testName: t2d-wald
                                    resTableId: outTable_01
                -   type: LogReg
                    subType: score
                    covariates:
                        -   table: inTable_01
                            cols:
                                - scores_1
                                - scores_2
                                - scores_3
                    responseVariables:
                        -   tableId: inTable_02
                            cols:
                                -   colName: t2d
                                    testName: t2d-score
                                    resTableId: outTable_01
                -   type: LinReg
                    covariates:
                        -   table: inTable_01
                            cols:
                                - scores_1
                                - scores_2
                                - scores_3
                    responseVariables:
                        -   tableId: inTable_02
                            cols:
                                -   colName: bmi
                                    testName: bmi-LinReg
                                    resTableId: outTable_01
        inouts:
            inMt:
                dataFileId: outMt
            outTable_01:
                dataFileId: outPval1
            inTable_01:
                dataFileId: pcaScore
            inTable_02:
                dataFileId: inPheno
                microFunctions:
                    -   type: keyBy
                        parameters:
                            keys:
                                - ID

    ASSOC2:
        specifications:
            function: HailAssociation
        parameters:
            tests:
                -   type: skat
                    covariates:
                        -   table: inTable_01
                            cols:
                                - scores_1
                                - scores_2
                                - scores_3
                    responseVariables:
                        -   tableId: inTable_02
                            cols:
                                -   colName: bmi
                                    testName: bmi-skat
                                    resTableId: outTable_02
                                    param:
                                        logistic: false
                                -   colName: t2d
                                    testName: t2d-skat
                                    resTableId: outTable_02
                                    param:
                                        logistic: true

                    keyExpr:
                        tableId: inTable_03
                        colName: gene_symbol

                    weightExpr:
                        tableId: inTable_03
                        colName: skat_weight
                    
        inouts:
            inMt:
                dataFileId: outMt
            outTable_02:
                dataFileId: outPval2
            inTable_01:
                dataFileId: pcaScore
            inTable_02:
                dataFileId: inPheno
                microFunctions:
                    -   type: keyBy
                        parameters:
                            keys:
                                - ID
            inTable_03:
                dataFileId: outGene