order:
    - IGTVCF
stages:
    IGTVCF:
        spec:
            function: ImportGenotype
        inout:
            inGt:
                direction: input
                path: 1kg.micro.vcf.bgz
            outGt:
                direction: output
                path: 1kg.ma.mt