config:
    mtPathMa: &mtPathMa 1kg.ma.mt
order:
    - IGTVCF
    - BRKMA
stages:
    IGTVCF:
        spec:
            function: ImportGenotype
        io:
            input:
                direction: input
                path: 1kg.micro.vcf.bgz
            output:
                direction: output
                path: *mtPathMa
    BRKMA:
        spec:
            function: SplitMulti
        arg:
            withHTS: true
        io:
            input:
                direction: input
                path: *mtPathMa
            output:
                direction: output
                path: 1kg.ba.mt