dataFiles:
    inVCF:
        disk:
            path: 1kg.micro.vcf.bgz
    outMT:
        disk:
            path: 1kg.ma.mt
        memory:

executionPlan:
    - IGTVCF
stages:
    IGTVCF:
        spec:
            function: CommonOperations
        io:
            inData:
                id: inVCF
                direction: input
            outData:
                id: outMT
                direction: output